INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Barkonian Banner D", "Barkonian-Banner-D.png", "https://startrekdesignproject.com/symbols/barkonian-banner-d/", "Beta", "2300s", "The Next Generation", "S07E16 Thine Own Self");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Barkonian-Banner-D.png", "Barkonian");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Barkonian-Banner-D.png", "Flag/Banner");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Barkonian-Banner-D.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Delta Flyer", "Delta-Flyer.png", "https://startrekdesignproject.com/symbols/delta-flyer/", "Alpha", "2300s", "Lower Decks", "S03E05 Reflections");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Delta-Flyer.png", "Sterfleet");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Delta-Flyer.png", "Starship");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Delta-Flyer.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Orion Outpost (Qualor II)", "Orion-Outpost-Qualor.png", "https://startrekdesignproject.com/symbols/orion-outpost-qualor-ii/", "Beta", "2300s", "Lower Decks", "S02E03 We'll Always Have Tom Paris");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Orion-Outpost-Qualor.png", "Orion");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Orion-Outpost-Qualor.png", "Qualor II");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Orion-Outpost-Qualor.png", "Sign/Poster");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Orion-Outpost-Qualor.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Sampaguita", "Sampaguita.png", "https://startrekdesignproject.com/symbols/sampaguita/", "Alpha", "2300s", "Lower Decks", "S03E05 Reflections");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Sampaguita.png", "Starship");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Sampaguita.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Starbase 80 Crew", "Starbase-80-Crew.png", "https://startrekdesignproject.com/symbols/starbase-80-crew/", "Alpha", "2300s", "Lower Decks", "S03E09 Trusted Sources");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Starbase-80-Crew.png", "Starfleet");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Starbase-80-Crew.png", "Insignia");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Starbase-80-Crew.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Starfleet Outpost Crew 2250s", "Starfleet-Outpost-Crew-2250s.png", "https://startrekdesignproject.com/symbols/starfleet-outpost-crew-2250s/", "Alpha", "2200s", "Strange New Worlds", "S01E10 A Quality of Mercy");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Starfleet-Outpost-Crew-2250s.png", "Starfleet");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Starfleet-Outpost-Crew-2250s.png", "Insignia");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Starfleet-Outpost-Crew-2250s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Truth Society", "Truth-Society.png", "https://startrekdesignproject.com/symbols/truth-society/", "Alpha", "2300s", "Lower Decks", "S03E05 Reflections");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Truth-Society.png", "Sign/Poster");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Truth-Society.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Tsunkatse Games Informal", "Tsunkatse-Informal.png", "https://startrekdesignproject.com/symbols/tsunkatse-games-informal/", "Delta", "2300s", "Voyager", "S06E15 ""Tsunkatse""");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Tsunkatse-Informal.png", "Tsunkatse Games");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Tsunkatse-Informal.png", "Sports");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Tsunkatse-Informal.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Widin Dairy Farm", "Widin-Dairy-Farm.png", "https://startrekdesignproject.com/symbols/widin-dairy-farm/", "Alpha", "1900s", "TOS", "S01E28 The City on the Edge of Forever");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Widin-Dairy-Farm.png", "Earth");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Widin-Dairy-Farm.png", "Commerce");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Widin-Dairy-Farm.png", "Prime");
