INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Andorian 2380s", "Andoria-2380s.png", "https://startrekdesignproject.com/symbols/andorian-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Andoria-2380s.png", "Andoria");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Andoria-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Andoria-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Argo Shuttle/Ground Transport", "Argo.png", "https://startrekdesignproject.com/symbols/argo-shuttle-ground-transport/", "Alpha", "2300s", "Movies", "Star Trek Nemesis");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Argo.png", "Starfleet");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Argo.png", "Starship");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Argo.png", "Transport");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Argo.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Breen 2370s", "Breen-2380s.png", "https://startrekdesignproject.com/symbols/breen-2370s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Breen-2380s.png", "Breen");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Breen-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Breen-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Gorn Hegemony", "Gorn.png", "https://startrekdesignproject.com/symbols/gorn-hegemony/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Gorn.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Gorn.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Klingon Kot'baval Banner D", "Klingon-Kot_baval-Banner-D.png", "https://startrekdesignproject.com/symbols/klingon-kot-baval-banner-d-1/", "Beta", "2300s", "The Next Generation", "S07E21 Firstborn");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Klingon-Kot_baval-Banner-D.png", "Klingon Empire");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Klingon-Kot_baval-Banner-D.png", "Flag/Banner");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Klingon-Kot_baval-Banner-D.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Krenim Imperium", "Krenim.png", "https://startrekdesignproject.com/symbols/krenim-imperium/", "Delta", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Krenim.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Krenim.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Multi-Mitt (Jankom Pog)", "Multi-Mitt.png", "https://startrekdesignproject.com/symbols/multi-mitt-jankom-pog/", "Alpha", "2300s", "Prodigy", "S01E20 Supernova, Part 2");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Multi-Mitt.png", "Tellarite");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Multi-Mitt.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Orion Syndicate 2380s", "Orion-Syndicate.png", "https://startrekdesignproject.com/symbols/orion-syndicate/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Orion-Syndicate.png", "Orion");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Orion-Syndicate.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Orion-Syndicate.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Ornaran 10K Run", "Ornaran-10K-Run.png", "https://startrekdesignproject.com/symbols/ornaran-10k-run/", "Alpha", "2300s", "None", "S03E09 Trusted Sources");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Ornaran-10K-Run.png", "Sports");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Ornaran-10K-Run.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Protostar Helm Control", "Protostar-Helm-Control.png", "https://startrekdesignproject.com/symbols/protostar-helm-control/", "Alpha", "2300s", "Prodigy", "S01E06 Kobayashi");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Protostar-Helm-Control.png", "Starfleet");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Protostar-Helm-Control.png", "Advisory");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Protostar-Helm-Control.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Q 2380s", "Q-2380s.png", "https://startrekdesignproject.com/symbols/q-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Q-2380s.png", "Q");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Q-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Q-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Reman 2380s", "Reman-2380s.png", "https://startrekdesignproject.com/symbols/reman-2380s/", "Beta", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Reman-2380s.png", "Romulan Star Empire");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Reman-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Reman-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Risian 2380s", "Risian-2380s.png", "https://startrekdesignproject.com/symbols/risian-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Risian-2380s.png", "Risa");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Risian-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Risian-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Risian Facial Mark B 3100s", "Risian-Facial-Mark-B-3100s.png", "https://startrekdesignproject.com/symbols/risian-facial-mark-b-3100s/", "Alpha", "3100s", "Discovery", "S04E13 Coming Home");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Risian-Facial-Mark-B-3100s.png", "Risa");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Risian-Facial-Mark-B-3100s.png", "Insignia");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Risian-Facial-Mark-B-3100s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Romulan Empire 2380s", "Romulan-2380s-E.png", "https://startrekdesignproject.com/symbols/romulan-empire-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Romulan-2380s-E.png", "Romulan Star Empire");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Romulan-2380s-E.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Romulan-2380s-E.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Andorian 2380s", "Andoria-2380s.png", "https://startrekdesignproject.com/symbols/andorian-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Andoria-2380s.png", "Andoria");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Andoria-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Andoria-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Argo Shuttle/Ground Transport", "Argo.png", "https://startrekdesignproject.com/symbols/argo-shuttle-ground-transport/", "Alpha", "2300s", "Movies", "Star Trek Nemesis");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Argo.png", "Starfleet");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Argo.png", "Starship");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Argo.png", "Transport");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Argo.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Breen 2370s", "Breen-2380s.png", "https://startrekdesignproject.com/symbols/breen-2370s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Breen-2380s.png", "Breen");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Breen-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Breen-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Gorn Hegemony", "Gorn.png", "https://startrekdesignproject.com/symbols/gorn-hegemony/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Gorn.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Gorn.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Klingon Kot'baval Banner D", "Klingon-Kot_baval-Banner-D.png", "https://startrekdesignproject.com/symbols/klingon-kot-baval-banner-d-1/", "Beta", "2300s", "The Next Generation", "S07E21 Firstborn");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Klingon-Kot_baval-Banner-D.png", "Klingon Empire");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Klingon-Kot_baval-Banner-D.png", "Flag/Banner");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Klingon-Kot_baval-Banner-D.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Krenim Imperium", "Krenim.png", "https://startrekdesignproject.com/symbols/krenim-imperium/", "Delta", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Krenim.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Krenim.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Multi-Mitt (Jankom Pog)", "Multi-Mitt.png", "https://startrekdesignproject.com/symbols/multi-mitt-jankom-pog/", "Alpha", "2300s", "Prodigy", "S01E20 Supernova, Part 2");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Multi-Mitt.png", "Tellarite");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Multi-Mitt.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Orion Syndicate 2380s", "Orion-Syndicate.png", "https://startrekdesignproject.com/symbols/orion-syndicate/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Orion-Syndicate.png", "Orion");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Orion-Syndicate.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Orion-Syndicate.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Ornaran 10K Run", "Ornaran-10K-Run.png", "https://startrekdesignproject.com/symbols/ornaran-10k-run/", "Alpha", "2300s", "None", "S03E09 Trusted Sources");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Ornaran-10K-Run.png", "Sports");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Ornaran-10K-Run.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Protostar Helm Control", "Protostar-Helm-Control.png", "https://startrekdesignproject.com/symbols/protostar-helm-control/", "Alpha", "2300s", "Prodigy", "S01E06 Kobayashi");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Protostar-Helm-Control.png", "Starfleet");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Protostar-Helm-Control.png", "Advisory");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Protostar-Helm-Control.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Q 2380s", "Q-2380s.png", "https://startrekdesignproject.com/symbols/q-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Q-2380s.png", "Q");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Q-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Q-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Reman 2380s", "Reman-2380s.png", "https://startrekdesignproject.com/symbols/reman-2380s/", "Beta", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Reman-2380s.png", "Romulan Star Empire");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Reman-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Reman-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Risian 2380s", "Risian-2380s.png", "https://startrekdesignproject.com/symbols/risian-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Risian-2380s.png", "Risa");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Risian-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Risian-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Risian Facial Mark B 3100s", "Risian-Facial-Mark-B-3100s.png", "https://startrekdesignproject.com/symbols/risian-facial-mark-b-3100s/", "Alpha", "3100s", "Discovery", "S04E13 Coming Home");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Risian-Facial-Mark-B-3100s.png", "Risa");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Risian-Facial-Mark-B-3100s.png", "Insignia");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Risian-Facial-Mark-B-3100s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Romulan Empire 2380s", "Romulan-2380s-E.png", "https://startrekdesignproject.com/symbols/romulan-empire-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Romulan-2380s-E.png", "Romulan Star Empire");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Romulan-2380s-E.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Romulan-2380s-E.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Andorian 2380s", "Andoria-2380s.png", "https://startrekdesignproject.com/symbols/andorian-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Andoria-2380s.png", "Andoria");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Andoria-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Andoria-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Argo Shuttle/Ground Transport", "Argo.png", "https://startrekdesignproject.com/symbols/argo-shuttle-ground-transport/", "Alpha", "2300s", "Movies", "Star Trek Nemesis");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Argo.png", "Starfleet");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Argo.png", "Starship");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Argo.png", "Transport");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Argo.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Breen 2370s", "Breen-2380s.png", "https://startrekdesignproject.com/symbols/breen-2370s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Breen-2380s.png", "Breen");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Breen-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Breen-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Gorn Hegemony", "Gorn.png", "https://startrekdesignproject.com/symbols/gorn-hegemony/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Gorn.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Gorn.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Klingon Kot'baval Banner D", "Klingon-Kot_baval-Banner-D.png", "https://startrekdesignproject.com/symbols/klingon-kot-baval-banner-d-1/", "Beta", "2300s", "The Next Generation", "S07E21 Firstborn");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Klingon-Kot_baval-Banner-D.png", "Klingon Empire");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Klingon-Kot_baval-Banner-D.png", "Flag/Banner");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Klingon-Kot_baval-Banner-D.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Krenim Imperium", "Krenim.png", "https://startrekdesignproject.com/symbols/krenim-imperium/", "Delta", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Krenim.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Krenim.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Multi-Mitt (Jankom Pog)", "Multi-Mitt.png", "https://startrekdesignproject.com/symbols/multi-mitt-jankom-pog/", "Alpha", "2300s", "Prodigy", "S01E20 Supernova, Part 2");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Multi-Mitt.png", "Tellarite");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Multi-Mitt.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Orion Syndicate 2380s", "Orion-Syndicate.png", "https://startrekdesignproject.com/symbols/orion-syndicate/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Orion-Syndicate.png", "Orion");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Orion-Syndicate.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Orion-Syndicate.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Ornaran 10K Run", "Ornaran-10K-Run.png", "https://startrekdesignproject.com/symbols/ornaran-10k-run/", "Alpha", "2300s", "None", "S03E09 Trusted Sources");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Ornaran-10K-Run.png", "Sports");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Ornaran-10K-Run.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Protostar Helm Control", "Protostar-Helm-Control.png", "https://startrekdesignproject.com/symbols/protostar-helm-control/", "Alpha", "2300s", "Prodigy", "S01E06 Kobayashi");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Protostar-Helm-Control.png", "Starfleet");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Protostar-Helm-Control.png", "Advisory");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Protostar-Helm-Control.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Q 2380s", "Q-2380s.png", "https://startrekdesignproject.com/symbols/q-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Q-2380s.png", "Q");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Q-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Q-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Reman 2380s", "Reman-2380s.png", "https://startrekdesignproject.com/symbols/reman-2380s/", "Beta", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Reman-2380s.png", "Romulan Star Empire");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Reman-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Reman-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Risian 2380s", "Risian-2380s.png", "https://startrekdesignproject.com/symbols/risian-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Risian-2380s.png", "Risa");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Risian-2380s.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Risian-2380s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Risian Facial Mark B 3100s", "Risian-Facial-Mark-B-3100s.png", "https://startrekdesignproject.com/symbols/risian-facial-mark-b-3100s/", "Alpha", "3100s", "Discovery", "S04E13 Coming Home");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Risian-Facial-Mark-B-3100s.png", "Risa");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Risian-Facial-Mark-B-3100s.png", "Insignia");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Risian-Facial-Mark-B-3100s.png", "Prime");
INSERT INTO badge_info (badge_name, badge_filename, badge_url, quadrant, time_period, franchise, reference) VALUES ("Romulan Empire 2380s", "Romulan-2380s-E.png", "https://startrekdesignproject.com/symbols/romulan-empire-2380s/", "Alpha", "2300s", "Prodigy", "S01E15 Masquerade");
INSERT IGNORE INTO badge_affiliation (badge_filename, affiliation_name) VALUES ("Romulan-2380s-E.png", "Romulan Star Empire");
INSERT IGNORE INTO badge_type (badge_filename, type_name) VALUES ("Romulan-2380s-E.png", "Species/Civilization");
INSERT IGNORE INTO badge_universe (badge_filename, universe_name) VALUES ("Romulan-2380s-E.png", "Prime");
