from .slots_symbol import *

basic_symbols = [
    SlotsSymbol(
        name="Janeway",
        effect_where="adjacent",
        effect_which="coffee",
        effect_self=True,
        effect_name="alter_payout",
        effect_args={"new_payout": 2},
        description="Gains 1 value whenever adjacent to coffee",
    ),
    SlotsSymbol(
        name="Picard",
        effect_where="adjacent",
        effect_which="combadge",
        effect_name="alter_payout",
        effect_args={"new_payout": 1},
        description="Increases in value near combadges",
    ),
    SlotsSymbol(
        name="Riker",
        effect_where="adjacent",
        effect_which="pants",
        effect_name="destroy",
        description="Destroys all adjacent pants",
    ),
    SlotsSymbol(name="Kirk"),
    SlotsSymbol(name="Coffee"),
    SlotsSymbol(name="Burnham"),
    SlotsSymbol(name="Pike"),
    SlotsSymbol(
        name="Sisko",
        effect_where="adjacent",
        effect_which="baseball glove",
        effect_name="alter_payout",
        effect_args={"new_payout": 1},
        description="He loves baseball!",
    ),
    SlotsSymbol(
        name="Kevin",
        effect_where="adjacent",
        effect_which="any",
        effect_name="destroy",
        effect_args={"payout": 1},
        description="Ice cream truck music can be heard in the distance",
    ),
    SlotsSymbol(name="Combadge"),
    SlotsSymbol(name="Fedora"),
    SlotsSymbol(name="Pants"),
    SlotsSymbol(name="Baseball Glove"),
    SlotsSymbol(name="Yelgrun"),
    SlotsSymbol(name="Mugato"),
    SlotsSymbol(
        name="Niners Rom",
        effect_where="adjacent",
        effect_which="baseball glove",
        effect_name="alter_payout",
        effect_args={"new_payout": 1},
    ),
    SlotsSymbol(name="Onezerozeroone"),
    SlotsSymbol(name="Kurros"),
    SlotsSymbol(name="Dominion Dukat"),
    SlotsSymbol(name="Commando Shran"),
    SlotsSymbol(name="Badgey"),
    SlotsSymbol(
        name="Armus",
        effect_where="adjacent",
        effect_which="any",
        effect_name="destroy",
        description="Destroys everything around it",
    ),
    SlotsSymbol(name="Admiral Nechayev"),
]

all_symbols = basic_symbols
